name: e_Chow
description: A food ordering and delivering app


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  get: ^4.1.4
  dots_indicator: ^2.0.0
  persistent_bottom_nav_bar: ^4.0.2
  shared_preferences: ^2.0.11
  intl: ^0.19.0


  cupertino_icons: ^1.0.2

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_app_name: ^0.1.1

  flutter_lints: ^2.0.0

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon/icon.png"
    min_sdk_android: 21

flutter_app_name:
  name: "e-Chow"




flutter:


  uses-material-design: true


  assets:
     - assets/images/

  fonts:
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto-Regular.ttf
           weight: 400
         - asset:  assets/fonts/Roboto-Medium.ttf
           weight: 500
         - asset: assets/fonts/Roboto-Bold.ttf
           weight: 700
         - asset: assets/fonts/Roboto-Black.ttf
           weight: 900
